# Generated by Django 5.1.2 on 2024-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('SSLcommerz', 'SSLcommerz'), ('PayPal', 'PayPal'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=30),
        ),
    ]
