# Generated by Django 5.1.2 on 2024-10-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_payement_id_order_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordee_id',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal'), ('SSLcommercez', 'SSLcommercez')], default='Cash on Delivery', max_length=30),
        ),
    ]
