# Generated by Django 5.1.2 on 2024-10-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Pending', 'Pending'), ('On the Way', 'On the Way'), ('Order Placed', 'Order Placed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=30),
        ),
    ]
