# Generated by Django 5.1.2 on 2024-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('SSLcommerz', 'SSLcommerz'), ('PayPal', 'PayPal'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('On the Way', 'On the Way'), ('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
