# Generated by Django 5.1.2 on 2024-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('SSLcommerz', 'SSLcommerz'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Delivered', 'Delivered'), ('On the Way', 'On the Way'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
