# Generated by Django 5.1.2 on 2024-10-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
